### ISSUE TITLE
Porting the Mod

### ISSUE THREAD

**Issue by PulseBeat02** [GenDeathrow/CutScenes-1.7.10#4]
Hey, this mod hasn't been updated for quite a while, and because it is listed as "All Rights Reserved", I can't port it to 1.12.2 and upload it onto Curseforge. Thus, I am asking for your permission if I could compile the code to run in 1.12.2. I really want to find a cut scene mod in 1.12.2 but I can't find any except this one, which is Forge and is version 1.7.10. Therefore, do I have the permission to port this mod to 1.12.2 and upload it there? Thanks.

**Comment by PulseBeat02** [comment]
If you don't want me to make a new project to do this, I could send you a file with the ported version and you can add it to the files in your curseforge project. I just want to see this mod function in 1.12.2, because 1.12.2 is like the new 1.7.10, where a ton of modpacks are being hosted in.

**Comment by GenDeathrow** [comment]
@PulseBeat02 Come find me over at Discord. https://discord.gg/dHrJ8U
